-- ============================================================================
-- NettOps Perú — Datos demo (contexto real de operaciones en Ica)
-- Ejecutar DESPUÉS de 01-schema.sql, en: Supabase → SQL Editor → Run
-- Es idempotente: puede re-ejecutarse (usa ON CONFLICT DO NOTHING).
-- Fecha de referencia del demo: 2026-08-08
-- ============================================================================

-- Clientes
insert into clientes (id,nombre,razon,ruc,contacto,cargo_contacto,telefono) values ('cli-01','Claro Perú','América Móvil Perú S.A.C.','20467534026','Renzo Salaverry Díaz','Jefe de Despliegue Región Sur','+51 997 412 305') on conflict (id) do nothing;
insert into clientes (id,nombre,razon,ruc,contacto,cargo_contacto,telefono) values ('cli-02','Entel Perú','Entel Perú S.A.','20106897914','Paola Injoque Ramírez','Coordinadora de O&M Ica','+51 986 220 174') on conflict (id) do nothing;
insert into clientes (id,nombre,razon,ruc,contacto,cargo_contacto,telefono) values ('cli-03','Bitel','Viettel Perú S.A.C.','20543254798','Luis Gambetta Herrera','Coordinador de Despliegue Nazca','+51 945 887 660') on conflict (id) do nothing;

-- Proyectos
insert into proyectos (id,codigo,cliente_id,nombre,descripcion,estado,inicio,fin,supervisor,presupuesto) values ('pry-01','PRY-2026-014','cli-01','Despliegue 5G NSA — Ica Metropolitana','Instalación y comisionamiento de portadora 5G n78 sobre 5 sitios existentes en Ica, Subtanjalla, La Tinguiña, Parcona y Los Aquijes.','en_ejecucion','2026-06-15','2026-09-30','Ing. Carlos Bendezú Rojas',486500) on conflict (id) do nothing;
insert into proyectos (id,codigo,cliente_id,nombre,descripcion,estado,inicio,fin,supervisor,presupuesto) values ('pry-02','PRY-2026-021','cli-02','Mantenimiento preventivo 2026 — Corredor Pisco–Chincha','Programa anual de mantenimiento preventivo y correctivo de 8 estaciones base del corredor costero Pisco–Chincha.','en_ejecucion','2026-07-01','2026-12-15','Ing. Carmen Falconí Espino',297800) on conflict (id) do nothing;
insert into proyectos (id,codigo,cliente_id,nombre,descripcion,estado,inicio,fin,supervisor,presupuesto) values ('pry-03','PRY-2026-009','cli-03','Ampliación 4G LTE — Corredor Nazca–Palpa','Construcción e integración de 47 sitios nuevos (greenfield y cohabitación) a lo largo del corredor Nazca–Palpa–Marcona. Fase 1: surveys y adecuaciones.','en_ejecucion','2026-08-01','2027-03-31','Ing. Carlos Bendezú Rojas',3120000) on conflict (id) do nothing;

-- Sitios (BTS) — 60 estaciones base
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-01','IC-ICA-0201','Azotea Galería Fénix','Calle Lima 245, Cercado de Ica','Ica','Ica',-14.06414,-75.72951,'Rooftop',18,array['2G','4G','5G'],'Red comercial + banco 48V','pry-01','operativo') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-02','IC-SUBTANJALLA-0117','Fundo La Máquina','Panamericana Sur km 296, Subtanjalla','Subtanjalla','Ica',-14.0111,-75.7519,'Greenfield',42,array['2G','3G','4G','5G'],'Red comercial + grupo electrógeno','pry-01','en_ejecucion') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-03','IC-TINGUINA-0064','Av. Progreso cdra. 8','Av. Progreso cdra. 8, La Tinguiña','La Tinguiña','Ica',-14.0394,-75.71484,'Monoposte',30,array['3G','4G'],'Red comercial + banco 48V','pry-01','operativo') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-04','IC-PARCONA-0233','Sector Acomayo','Calle Los Álamos s/n, sector Acomayo, Parcona','Parcona','Ica',-14.0417,-75.6931,'Greenfield',36,array['2G','3G','4G'],'Red comercial + banco 48V','pry-01','alarma') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-05','IC-AQUIJES-0158','Cruce Los Aquijes','Carretera Ica–Los Aquijes km 7.5','Los Aquijes','Ica',-14.0967,-75.6892,'Greenfield',42,array['3G','4G'],'Red comercial','pry-01','en_ejecucion') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-06','IC-PISCO-0342','Pisco Centro','Av. San Martín 890, Pisco','Pisco','Pisco',-13.7103,-76.2032,'Rooftop',15,array['2G','3G','4G'],'Red comercial + banco 48V','pry-02','operativo') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-07','IC-SANANDRES-0091','San Andrés Malecón','Malecón San Martín s/n, San Andrés','San Andrés','Pisco',-13.7444,-76.2236,'Monoposte',24,array['3G','4G'],'Red comercial + banco 48V','pry-02','operativo') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-08','IC-TUPACAMARU-0125','Túpac Amaru Inca','Av. Fermín Tangüis cdra. 12, Túpac Amaru Inca','Túpac Amaru Inca','Pisco',-13.7189,-76.1628,'Greenfield',36,array['2G','3G','4G'],'Red comercial + banco 48V','pry-02','operativo') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-09','IC-PARACAS-0288','El Chaco — Paracas','Av. Paracas s/n, El Chaco, Paracas','Paracas','Pisco',-13.8339,-76.2503,'Camuflado (palmera)',21,array['3G','4G'],'Red comercial + banco 48V','pry-02','operativo') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-10','IC-CHINCHA-0412','Chincha Alta Centro','Calle Mariscal Castilla 570, Chincha Alta','Chincha Alta','Chincha',-13.4099,-76.1323,'Rooftop',20,array['2G','3G','4G'],'Red comercial + banco 48V','pry-02','operativo') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-11','IC-SUNAMPE-0176','Sunampe Norte','Prolongación Av. Benavides s/n, Sunampe','Sunampe','Chincha',-13.4181,-76.1447,'Monoposte',27,array['3G','4G'],'Red comercial','pry-02','operativo') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-12','IC-PUEBLONUEVO-0083','Pueblo Nuevo — Chincha','Av. Óscar R. Benavides cdra. 4, Pueblo Nuevo','Pueblo Nuevo','Chincha',-13.3961,-76.1281,'Greenfield',33,array['2G','3G','4G'],'Red comercial + banco 48V','pry-02','operativo') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-13','IC-GROCIOPRADO-0147','Grocio Prado','Calle Lima s/n, cerca al Santuario Beatita de Humay, Grocio Prado','Grocio Prado','Chincha',-13.3947,-76.1547,'Monoposte',24,array['3G','4G'],'Red comercial','pry-02','operativo') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-14','IC-NAZCA-0509','Nazca Centro','Jr. Bolognesi 371, Nazca','Nazca','Nazca',-14.828,-74.937,'Rooftop',16,array['2G','3G','4G'],'Red comercial + banco 48V','pry-03','en_ejecucion') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-15','IC-VISTAALEGRE-0521','Vista Alegre','Panamericana Sur km 447, Vista Alegre, Nazca','Vista Alegre','Nazca',-14.8397,-74.9256,'Greenfield',39,array['3G','4G'],'Red comercial + banco 48V','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-16','IC-PALPA-0530','Palpa — km 3','Corredor Nazca–Palpa, sector Palpa','Palpa','Palpa',-14.5586,-75.2106,'Monoposte',30,array['4G'],'Solar + banco 48V','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-17','IC-ELINGENIO-0531','El Ingenio — km 10','Corredor Nazca–Palpa, sector El Ingenio','El Ingenio','Nazca',-14.6247,-75.0598,'Greenfield',36,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-18','IC-CHANGUILLO-0532','Changuillo — km 17','Corredor Nazca–Palpa, sector Changuillo','Changuillo','Nazca',-14.5774,-75.2107,'Greenfield',42,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-19','IC-LLIPATA-0533','Llipata — km 24','Corredor Nazca–Palpa, sector Llipata','Llipata','Palpa',-14.5726,-75.1554,'Greenfield',48,array['4G'],'Solar + banco 48V','pry-03','en_ejecucion') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-20','IC-RIOGRANDE-0534','Río Grande — km 31','Corredor Nazca–Palpa, sector Río Grande','Río Grande','Palpa',-14.492,-75.218,'Monoposte',30,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-21','IC-MARCONA-0535','San Juan de Marcona — km 38','Corredor Nazca–Palpa, sector San Juan de Marcona','San Juan de Marcona','Nazca',-15.3497,-75.1736,'Greenfield',36,array['4G'],'Red comercial','pry-03','operativo') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-22','IC-CAHUACHI-0536','Cahuachi — km 45','Corredor Nazca–Palpa, sector Cahuachi','Cahuachi','Nazca',-14.8188,-75.1251,'Greenfield',42,array['4G'],'Solar + banco 48V','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-23','IC-CANTALLOC-0537','Cerro San Juan Bautista de la Pampa de los Castillos — acceso por camino carrozable km 12.5 desde el desvío de la Panamericana Sur','Corredor Nazca–Palpa, sector Cantalloc','Cantalloc','Nazca',-14.8427,-74.9129,'Greenfield',48,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-24','IC-SOISONGO-0538','Soisongo — km 59','Corredor Nazca–Palpa, sector Soisongo','Soisongo','Nazca',-14.769,-74.951,'Monoposte',30,array['4G'],'Red comercial','pry-03','en_ejecucion') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-25','IC-ORCONA-0539','Orcona — km 6','Corredor Nazca–Palpa, sector Orcona','Orcona','Nazca',-14.797,-74.963,'Greenfield',36,array['4G'],'Solar + banco 48V','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-26','IC-SANPABLO-0540','San Pablo — km 13','Corredor Nazca–Palpa, sector San Pablo','San Pablo','Palpa',-14.47,-75.21,'Greenfield',42,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-27','IC-SACRAMENTO-0541','Sacramento — km 20','Corredor Nazca–Palpa, sector Sacramento','Sacramento','Palpa',-14.563,-75.162,'Greenfield',48,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-28','IC-PALPA-0542','Palpa 3 — km 27','Corredor Nazca–Palpa, sector Palpa','Palpa','Palpa',-14.5146,-75.1746,'Monoposte',30,array['4G'],'Solar + banco 48V','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-29','IC-ELINGENIO-0543','El Ingenio 3 — km 34','Corredor Nazca–Palpa, sector El Ingenio','El Ingenio','Nazca',-14.6307,-75.0238,'Greenfield',36,array['4G'],'Red comercial','pry-03','en_ejecucion') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-30','IC-CHANGUILLO-0544','Changuillo 3 — km 41','Corredor Nazca–Palpa, sector Changuillo','Changuillo','Nazca',-14.5834,-75.1747,'Greenfield',42,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-31','IC-LLIPATA-0545','Llipata 3 — km 48','Corredor Nazca–Palpa, sector Llipata','Llipata','Palpa',-14.5786,-75.1194,'Greenfield',48,array['4G'],'Solar + banco 48V','pry-03','operativo') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-32','IC-RIOGRANDE-0546','Río Grande 3 — km 55','Corredor Nazca–Palpa, sector Río Grande','Río Grande','Palpa',-14.498,-75.182,'Monoposte',30,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-33','IC-MARCONA-0547','San Juan de Marcona 3 — km 62','Corredor Nazca–Palpa, sector San Juan de Marcona','San Juan de Marcona','Nazca',-15.3557,-75.1876,'Greenfield',36,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-34','IC-CAHUACHI-0548','Cahuachi 3 — km 9','Corredor Nazca–Palpa, sector Cahuachi','Cahuachi','Nazca',-14.8248,-75.1391,'Greenfield',42,array['4G'],'Solar + banco 48V','pry-03','en_ejecucion') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-35','IC-CANTALLOC-0549','Cantalloc 3 — km 16','Corredor Nazca–Palpa, sector Cantalloc','Cantalloc','Nazca',-14.8487,-74.9269,'Greenfield',48,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-36','IC-SOISONGO-0550','Soisongo 3 — km 23','Corredor Nazca–Palpa, sector Soisongo','Soisongo','Nazca',-14.775,-74.965,'Monoposte',30,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-37','IC-ORCONA-0551','Orcona 3 — km 30','Corredor Nazca–Palpa, sector Orcona','Orcona','Nazca',-14.803,-74.977,'Greenfield',36,array['4G'],'Solar + banco 48V','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-38','IC-SANPABLO-0552','San Pablo 3 — km 37','Corredor Nazca–Palpa, sector San Pablo','San Pablo','Palpa',-14.476,-75.224,'Greenfield',42,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-39','IC-SACRAMENTO-0553','Sacramento 3 — km 44','Corredor Nazca–Palpa, sector Sacramento','Sacramento','Palpa',-14.569,-75.176,'Greenfield',48,array['4G'],'Red comercial','pry-03','en_ejecucion') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-40','IC-PALPA-0554','Palpa 4 — km 51','Corredor Nazca–Palpa, sector Palpa','Palpa','Palpa',-14.5206,-75.1886,'Monoposte',30,array['4G'],'Solar + banco 48V','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-41','IC-ELINGENIO-0555','El Ingenio 4 — km 58','Corredor Nazca–Palpa, sector El Ingenio','El Ingenio','Nazca',-14.6367,-75.0378,'Greenfield',36,array['4G'],'Red comercial','pry-03','operativo') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-42','IC-CHANGUILLO-0556','Changuillo 4 — km 5','Corredor Nazca–Palpa, sector Changuillo','Changuillo','Nazca',-14.5894,-75.1887,'Greenfield',42,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-43','IC-LLIPATA-0557','Llipata 4 — km 12','Corredor Nazca–Palpa, sector Llipata','Llipata','Palpa',-14.5346,-75.1334,'Greenfield',48,array['4G'],'Solar + banco 48V','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-44','IC-RIOGRANDE-0558','Río Grande 4 — km 19','Corredor Nazca–Palpa, sector Río Grande','Río Grande','Palpa',-14.504,-75.196,'Monoposte',30,array['4G'],'Red comercial','pry-03','en_ejecucion') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-45','IC-MARCONA-0559','San Juan de Marcona 4 — km 26','Corredor Nazca–Palpa, sector San Juan de Marcona','San Juan de Marcona','Nazca',-15.3617,-75.1516,'Greenfield',36,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-46','IC-CAHUACHI-0560','Cahuachi 4 — km 33','Corredor Nazca–Palpa, sector Cahuachi','Cahuachi','Nazca',-14.8308,-75.1031,'Greenfield',42,array['4G'],'Solar + banco 48V','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-47','IC-CANTALLOC-0561','Cantalloc 4 — km 40','Corredor Nazca–Palpa, sector Cantalloc','Cantalloc','Nazca',-14.8047,-74.8909,'Greenfield',48,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-48','IC-SOISONGO-0562','Soisongo 4 — km 47','Corredor Nazca–Palpa, sector Soisongo','Soisongo','Nazca',-14.781,-74.929,'Monoposte',30,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-49','IC-ORCONA-0563','Orcona 4 — km 54','Corredor Nazca–Palpa, sector Orcona','Orcona','Nazca',-14.809,-74.941,'Greenfield',36,array['4G'],'Solar + banco 48V','pry-03','en_ejecucion') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-50','IC-SANPABLO-0564','San Pablo 4 — km 61','Corredor Nazca–Palpa, sector San Pablo','San Pablo','Palpa',-14.482,-75.238,'Greenfield',42,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-51','IC-SACRAMENTO-0565','Sacramento 4 — km 8','Corredor Nazca–Palpa, sector Sacramento','Sacramento','Palpa',-14.525,-75.19,'Greenfield',48,array['4G'],'Red comercial','pry-03','operativo') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-52','IC-PALPA-0566','Palpa 5 — km 15','Corredor Nazca–Palpa, sector Palpa','Palpa','Palpa',-14.5266,-75.2026,'Monoposte',30,array['4G'],'Solar + banco 48V','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-53','IC-ELINGENIO-0567','El Ingenio 5 — km 22','Corredor Nazca–Palpa, sector El Ingenio','El Ingenio','Nazca',-14.6427,-75.0518,'Greenfield',36,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-54','IC-CHANGUILLO-0568','Changuillo 5 — km 29','Corredor Nazca–Palpa, sector Changuillo','Changuillo','Nazca',-14.5954,-75.2027,'Greenfield',42,array['4G'],'Red comercial','pry-03','en_ejecucion') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-55','IC-LLIPATA-0569','Llipata 5 — km 36','Corredor Nazca–Palpa, sector Llipata','Llipata','Palpa',-14.5406,-75.1474,'Greenfield',48,array['4G'],'Solar + banco 48V','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-56','IC-RIOGRANDE-0570','Río Grande 5 — km 43','Corredor Nazca–Palpa, sector Río Grande','Río Grande','Palpa',-14.51,-75.21,'Monoposte',30,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-57','IC-MARCONA-0571','San Juan de Marcona 5 — km 50','Corredor Nazca–Palpa, sector San Juan de Marcona','San Juan de Marcona','Nazca',-15.3677,-75.1656,'Greenfield',36,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-58','IC-CAHUACHI-0572','Cahuachi 5 — km 57','Corredor Nazca–Palpa, sector Cahuachi','Cahuachi','Nazca',-14.8368,-75.1171,'Greenfield',42,array['4G'],'Solar + banco 48V','pry-03','planificado') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-59','IC-CANTALLOC-0573','Cantalloc 5 — km 4','Corredor Nazca–Palpa, sector Cantalloc','Cantalloc','Nazca',-14.8107,-74.9049,'Greenfield',48,array['4G'],'Red comercial','pry-03','en_ejecucion') on conflict (id) do nothing;
insert into sitios (id,codigo,nombre,direccion,distrito,provincia,lat,lng,tipo,altura,tecnologias,energia,proyecto_id,estado) values ('st-60','IC-SOISONGO-0574','Soisongo 5 — km 11','Corredor Nazca–Palpa, sector Soisongo','Soisongo','Nazca',-14.787,-74.943,'Monoposte',30,array['4G'],'Red comercial','pry-03','planificado') on conflict (id) do nothing;

-- Técnicos
insert into tecnicos (id,nombre,dni,rol,especialidad,telefono,foto,estado,zona,certificaciones) values ('tec-01','Rosa Quispe Huamán','43765210','Líder de cuadrilla','RF e instalación','+51 956 102 447','https://i.pravatar.cc/128?img=47','en_campo','Ica',array['Trabajos en altura','Primeros auxilios','Manejo defensivo']) on conflict (id) do nothing;
insert into tecnicos (id,nombre,dni,rol,especialidad,telefono,foto,estado,zona,certificaciones) values ('tec-02','Marco Ccahuana Flores','46882301','Técnico RF','Antenas y RRU','+51 987 334 210','https://i.pravatar.cc/128?img=12','en_campo','Ica',array['Trabajos en altura']) on conflict (id) do nothing;
insert into tecnicos (id,nombre,dni,rol,especialidad,telefono,foto,estado,zona,certificaciones) values ('tec-03','Jorge Aparcana Donayre','41230976','Técnico electricista','Energía y climatización','+51 945 771 803','https://i.pravatar.cc/128?img=33','en_campo','Pisco–Chincha',array['Electricista industrial CONFIEP','Primeros auxilios']) on conflict (id) do nothing;
insert into tecnicos (id,nombre,dni,rol,especialidad,telefono,foto,estado,zona,certificaciones) values ('tec-04','Lucía Uchuya Mesías','47119842','Técnico de transmisión','Mediciones PIM / VSWR / MW','+51 998 450 122','https://i.pravatar.cc/128?img=45','disponible','Ica',array['Anritsu certified','Trabajos en altura']) on conflict (id) do nothing;
insert into tecnicos (id,nombre,dni,rol,especialidad,telefono,foto,estado,zona,certificaciones) values ('tec-05','César Yataco Magallanes','40587123','Rigger / torrero','Estructuras e izaje','+51 956 889 034',null,'en_campo','Ica–Nazca',array['Trabajos en altura','Izaje y rigging nivel II']) on conflict (id) do nothing;
insert into tecnicos (id,nombre,dni,rol,especialidad,telefono,foto,estado,zona,certificaciones) values ('tec-06','Alberto Peña Tasayco','44903218','Técnico de energía','Rectificadores y baterías','+51 987 210 559','https://i.pravatar.cc/128?img=60','en_campo','Pisco–Chincha',array['Electricista industrial']) on conflict (id) do nothing;
insert into tecnicos (id,nombre,dni,rol,especialidad,telefono,foto,estado,zona,certificaciones) values ('tec-07','Milagros Huarcaya Ventura','48332075','Técnico de comisionamiento','Integración 4G/5G','+51 944 605 918','https://i.pravatar.cc/128?img=25','en_campo','Ica',array['Huawei HCIA-5G']) on conflict (id) do nothing;
insert into tecnicos (id,nombre,dni,rol,especialidad,telefono,foto,estado,zona,certificaciones) values ('tec-08','Pedro Anicama Chacaliaza','42776590','Rigger / torrero','Estructuras y pintura','+51 956 118 274',null,'descanso','Pisco–Chincha',array['Trabajos en altura']) on conflict (id) do nothing;
insert into tecnicos (id,nombre,dni,rol,especialidad,telefono,foto,estado,zona,certificaciones) values ('tec-09','Katherine Ramos Cabrera','49015623','Drive tester','Medición de cobertura','+51 999 306 481','https://i.pravatar.cc/128?img=32','en_campo','Ica',array['TEMS Investigation','Manejo defensivo']) on conflict (id) do nothing;
insert into tecnicos (id,nombre,dni,rol,especialidad,telefono,foto,estado,zona,certificaciones) values ('tec-10','Víctor Mendoza Levano','40118736','Técnico correctivo','Correctivos multi-marca','+51 987 664 090','https://i.pravatar.cc/128?img=14','inactivo','Ica',array['Electricista industrial']) on conflict (id) do nothing;

-- Tipos de actividad
insert into tipos_actividad (id,nombre,categoria,dur_horas) values ('ta-01','Site survey (TSS)','Ingeniería',4) on conflict (id) do nothing;
insert into tipos_actividad (id,nombre,categoria,dur_horas) values ('ta-02','Instalación de gabinete outdoor','Instalación',8) on conflict (id) do nothing;
insert into tipos_actividad (id,nombre,categoria,dur_horas) values ('ta-03','Instalación de antenas RF','Instalación',8) on conflict (id) do nothing;
insert into tipos_actividad (id,nombre,categoria,dur_horas) values ('ta-04','Instalación de RRU','Instalación',5) on conflict (id) do nothing;
insert into tipos_actividad (id,nombre,categoria,dur_horas) values ('ta-05','Tendido de jumpers y fibra','Instalación',4) on conflict (id) do nothing;
insert into tipos_actividad (id,nombre,categoria,dur_horas) values ('ta-06','Sistema de puesta a tierra','Instalación',6) on conflict (id) do nothing;
insert into tipos_actividad (id,nombre,categoria,dur_horas) values ('ta-07','Comisionamiento 5G NSA','Comisionamiento',9) on conflict (id) do nothing;
insert into tipos_actividad (id,nombre,categoria,dur_horas) values ('ta-08','Integración a red y pruebas','Comisionamiento',4) on conflict (id) do nothing;
insert into tipos_actividad (id,nombre,categoria,dur_horas) values ('ta-09','Drive test','Calidad',6) on conflict (id) do nothing;
insert into tipos_actividad (id,nombre,categoria,dur_horas) values ('ta-10','Mantenimiento preventivo','Mantenimiento',5) on conflict (id) do nothing;
insert into tipos_actividad (id,nombre,categoria,dur_horas) values ('ta-11','Mantenimiento correctivo','Mantenimiento',4) on conflict (id) do nothing;
insert into tipos_actividad (id,nombre,categoria,dur_horas) values ('ta-12','Medición de PIM','Calidad',3) on conflict (id) do nothing;
insert into tipos_actividad (id,nombre,categoria,dur_horas) values ('ta-13','Medición de ROE / VSWR','Calidad',2.5) on conflict (id) do nothing;
insert into tipos_actividad (id,nombre,categoria,dur_horas) values ('ta-14','Alineación de microondas','Transmisión',5) on conflict (id) do nothing;
insert into tipos_actividad (id,nombre,categoria,dur_horas) values ('ta-15','Cambio de banco de baterías','Mantenimiento',4) on conflict (id) do nothing;
insert into tipos_actividad (id,nombre,categoria,dur_horas) values ('ta-16','Adecuación estructural de torre','Obra civil',9) on conflict (id) do nothing;
insert into tipos_actividad (id,nombre,categoria,dur_horas) values ('ta-17','Pintado y señalética','Obra civil',7) on conflict (id) do nothing;

-- Actividades
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0001','ta-01','st-02','pry-01','2026-07-27','08:00','12:30','08:05','12:20','completada','Acceso por trocha afirmada en buen estado. Se coordinó con el propietario del fundo el ingreso de grúa para el izaje.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0002','ta-02','st-02','pry-01','2026-07-29','07:30','15:30','07:40','15:55','completada','Gabinete OD fijado sobre losa nueva. Pernos de anclaje M16 torqueados a 110 Nm. Acta firmada por supervisor de Claro.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0003','ta-03','st-02','pry-01','2026-07-31','08:00','16:00','08:10','16:40','completada','Sectores instalados az 40° / 160° / 280°, tilt mecánico 2°. Se reemplazó una abrazadera con hilo barrido.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0004','ta-04','st-02','pry-01','2026-08-03','08:30','13:30','08:32','13:10','completada','Tres RRU n78 montadas en mástil, alimentación DC verificada 53.2 V.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0005','ta-05','st-02','pry-01','2026-08-04','08:00','12:00','08:15','11:35','completada','Jumpers 1/2" rotulados en ambos extremos. Pérdida de retorno OK en los 3 sectores.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0006','ta-12','st-01','pry-01','2026-08-05','09:00','12:00','09:05','11:50','completada','PIM -153 dBc en S1 y S2. S3 en -148 dBc, dentro de umbral del cliente.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0007','ta-10','st-06','pry-02','2026-08-04','08:00','13:00','08:02','12:45','completada','Limpieza de filtros y ajuste de breakers. Bornes del banco con sulfatación leve, se limpiaron y engrasaron.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0008','ta-10','st-07','pry-02','2026-08-05','08:00','13:00','08:10','12:40','completada','Sitio con brisa marina fuerte: se reforzó protección anticorrosiva en conectores exteriores.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0009','ta-13','st-10','pry-02','2026-08-06','09:00','11:30','09:12','11:25','completada','VSWR máximo 1.18 en sector 2. Sin hallazgos.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0010','ta-15','st-08','pry-02','2026-08-06','08:00','12:00','08:05','11:55','completada','Banco 48V 155Ah reemplazado. Autonomía medida 4h10 tras prueba de descarga. Banco retirado quedó en almacén Pisco.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0011','ta-09','st-01','pry-01','2026-08-07','07:00','13:00','07:03','13:20','completada','Ruta centro de Ica + anillo vial. RSRP promedio -84 dBm en clúster. Log entregado a optimización.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0012','ta-10','st-11','pry-02','2026-08-07','08:00','12:30','08:20','12:55','en_revision','Preventivo ejecutado sin evidencia fotográfica por falla de cámara del móvil; se regularizará en próxima visita.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0013','ta-07','st-02','pry-01','2026-08-08','08:00','17:00','08:12',null,'en_ejecucion','Script de integración cargado. A la espera de ventana de RAN para activar portadora.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0014','ta-10','st-12','pry-02','2026-08-08','08:00','13:00','08:05',null,'en_ejecucion','Termomagnético del aire acondicionado se dispara al arranque; en revisión antes de continuar con limpieza.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0015','ta-16','st-14','pry-03','2026-08-08','07:30','16:30','07:45',null,'en_ejecucion','Refuerzo de torreta para nueva carga de antenas. Pernos con corrosión severa hallados en cara B (ver INC-2026-041).') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0016','ta-08','st-02','pry-01','2026-08-08','15:00','19:00',null,null,'pendiente','Depende del comisionamiento ACT-0013. Ventana nocturna aprobada por el NOC de Claro.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0017','ta-09','st-02','pry-01','2026-08-10','07:00','13:00',null,null,'pendiente','') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0018','ta-10','st-13','pry-02','2026-08-08','14:30','19:00',null,null,'pendiente','Segunda visita del día para la cuadrilla de energía; coordinar llaves con el guardián del predio.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0019','ta-12','st-03','pry-01','2026-08-11','09:00','12:00',null,null,'pendiente','') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0020','ta-01','st-18','pry-03','2026-08-11','08:00','12:00',null,null,'pendiente','Coordinar acceso con municipalidad de Palpa.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0021','ta-01','st-19','pry-03','2026-08-12','08:00','12:00',null,null,'pendiente','') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0022','ta-14','st-15','pry-03','2026-08-12','09:00','14:00',null,null,'pendiente','Enlace VistaAlegre–Nazca Centro, alinear con nivel y RSL objetivo -38 dBm.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0023','ta-17','st-09','pry-02','2026-08-13','08:00','15:00',null,null,'pendiente','SERNANP exige pintura camuflada tono palmera; usar RAL aprobado.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0024','ta-11','st-04','pry-01','2026-08-06','14:00','18:00',null,null,'retrasada','Rectificador de reemplazo aún en tránsito desde Lima (guía 004-2231). Sitio opera a baterías con autonomía limitada.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0025','ta-03','st-05','pry-01','2026-08-05','08:00','16:00',null,null,'retrasada','Viento sostenido > 45 km/h en la zona; izaje suspendido por seguridad. Reprogramar con parte meteorológico favorable.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0026','ta-10','st-09','pry-02','2026-08-07','14:00','17:00',null,null,'retrasada','Cuadrilla retenida en Pueblo Nuevo por correctivo no programado.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0027','ta-12','st-02','pry-01','2026-08-07','14:00','17:00',null,null,'retrasada','Analizador PIM en calibración anual; retorna el 10/08.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0028','ta-09','st-14','pry-03','2026-08-03','07:00','13:00',null,null,'cancelada','Cliente pospuso la ventana de medición hasta integrar el segundo sitio del clúster.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0029','ta-17','st-13','pry-02','2026-07-30','08:00','15:00',null,null,'cancelada','Municipalidad observó permiso de trabajos en vía pública; se reingresó expediente.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0030','ta-06','st-15','pry-03','2026-08-02','08:00','14:00',null,null,'cancelada','Se reprogramará junto con la adecuación estructural para un solo viaje a Nazca.') on conflict (id) do nothing;
insert into actividades (id,tipo_id,sitio_id,proyecto_id,fecha,h_ini,h_fin,inicio_real,fin_real,estado,obs) values ('ACT-0031','ta-09','st-03','pry-01','2026-08-08','15:30','18:30',null,null,'pendiente','Ventana solicitada por el cliente con la cuadrilla ya comprometida; revisar el cruce de Marco Ccahuana con ACT-0013.') on conflict (id) do nothing;

-- Cuadrillas asignadas
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0001','tec-01') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0001','tec-05') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0002','tec-05') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0002','tec-06') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0003','tec-01') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0003','tec-02') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0003','tec-05') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0004','tec-02') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0005','tec-02') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0005','tec-04') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0006','tec-04') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0007','tec-03') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0007','tec-06') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0008','tec-03') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0008','tec-06') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0009','tec-04') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0010','tec-06') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0011','tec-09') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0012','tec-03') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0013','tec-07') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0013','tec-02') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0014','tec-03') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0014','tec-06') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0015','tec-05') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0015','tec-08') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0016','tec-07') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0017','tec-09') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0018','tec-03') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0018','tec-06') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0019','tec-04') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0020','tec-01') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0021','tec-01') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0022','tec-04') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0023','tec-08') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0024','tec-06') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0025','tec-01') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0025','tec-05') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0026','tec-03') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0027','tec-04') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0028','tec-09') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0029','tec-08') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0030','tec-06') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0031','tec-09') on conflict do nothing;
insert into actividad_tecnicos (actividad_id,tecnico_id) values ('ACT-0031','tec-02') on conflict do nothing;

-- Checklists de trabajo
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0013',0,'Verificar alimentación DC de RRU (53 V ± 1)',true where not exists (select 1 from checklist_items where actividad_id='ACT-0013' and orden=0);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0013',1,'Cargar datafill y script de comisionamiento',true where not exists (select 1 from checklist_items where actividad_id='ACT-0013' and orden=1);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0013',2,'Prueba de VSWR por sector',true where not exists (select 1 from checklist_items where actividad_id='ACT-0013' and orden=2);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0013',3,'Sincronización GPS / 1588v2',true where not exists (select 1 from checklist_items where actividad_id='ACT-0013' and orden=3);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0013',4,'Activar portadora n78 100 MHz',true where not exists (select 1 from checklist_items where actividad_id='ACT-0013' and orden=4);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0013',5,'Prueba de tráfico con UE de prueba',false where not exists (select 1 from checklist_items where actividad_id='ACT-0013' and orden=5);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0013',6,'KPIs iniciales dentro de umbral',false where not exists (select 1 from checklist_items where actividad_id='ACT-0013' and orden=6);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0013',7,'Acta de comisionamiento firmada',false where not exists (select 1 from checklist_items where actividad_id='ACT-0013' and orden=7);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0014',0,'Inspección visual de torre y anclajes',true where not exists (select 1 from checklist_items where actividad_id='ACT-0014' and orden=0);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0014',1,'Medición de tierra (< 5 Ω)',true where not exists (select 1 from checklist_items where actividad_id='ACT-0014' and orden=1);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0014',2,'Limpieza de filtros de aire acondicionado',true where not exists (select 1 from checklist_items where actividad_id='ACT-0014' and orden=2);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0014',3,'Prueba de grupo electrógeno en carga',true where not exists (select 1 from checklist_items where actividad_id='ACT-0014' and orden=3);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0014',4,'Revisión de banco de baterías',true where not exists (select 1 from checklist_items where actividad_id='ACT-0014' and orden=4);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0014',5,'Ajuste y torque de conexiones DC',true where not exists (select 1 from checklist_items where actividad_id='ACT-0014' and orden=5);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0014',6,'Verificación de alarmas remotas con NOC',false where not exists (select 1 from checklist_items where actividad_id='ACT-0014' and orden=6);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0014',7,'Limpieza general de sala/gabinete',false where not exists (select 1 from checklist_items where actividad_id='ACT-0014' and orden=7);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0014',8,'Rotulado y orden de cables',false where not exists (select 1 from checklist_items where actividad_id='ACT-0014' and orden=8);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0014',9,'Registro fotográfico final',false where not exists (select 1 from checklist_items where actividad_id='ACT-0014' and orden=9);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0015',0,'Señalización y delimitación de área',true where not exists (select 1 from checklist_items where actividad_id='ACT-0015' and orden=0);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0015',1,'Desmontaje de soportes obsoletos',true where not exists (select 1 from checklist_items where actividad_id='ACT-0015' and orden=1);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0015',2,'Instalación de refuerzos verticales',false where not exists (select 1 from checklist_items where actividad_id='ACT-0015' and orden=2);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0015',3,'Cambio de pernería observada',false where not exists (select 1 from checklist_items where actividad_id='ACT-0015' and orden=3);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0015',4,'Torque final y verificación',false where not exists (select 1 from checklist_items where actividad_id='ACT-0015' and orden=4);
insert into checklist_items (actividad_id,orden,texto,ok) select 'ACT-0015',5,'Registro fotográfico',false where not exists (select 1 from checklist_items where actividad_id='ACT-0015' and orden=5);

-- Incidencias
insert into incidencias (id,titulo,descripcion,severidad,estado,sitio_id,actividad_id,reportado_por,asignado_a,fecha,hora,fecha_limite,fecha_resolucion) values ('INC-2026-038','Rectificador principal fuera de servicio','BTS Parcona opera solo a baterías desde el 31/07. Rectificador Emerson R48-3000 no enciende, presunto daño en etapa de potencia tras corte de red comercial. Autonomía restante estimada: crítica.','critica','abierta','st-04','ACT-0024','tec-06','tec-06','2026-07-31','09:40','2026-08-02',null) on conflict (id) do nothing;
insert into incidencias (id,titulo,descripcion,severidad,estado,sitio_id,actividad_id,reportado_por,asignado_a,fecha,hora,fecha_limite,fecha_resolucion) values ('INC-2026-041','Corrosión severa en pernos de torreta','Durante adecuación en Nazca Centro se hallaron 6 pernos de la cara B con corrosión avanzada y pérdida de sección. Se requiere cambio antes de montar nueva carga.','alta','en_atencion','st-14','ACT-0015','tec-05','tec-05','2026-08-06','11:15','2026-08-12',null) on conflict (id) do nothing;
insert into incidencias (id,titulo,descripcion,severidad,estado,sitio_id,actividad_id,reportado_por,asignado_a,fecha,hora,fecha_limite,fecha_resolucion) values ('INC-2026-042','Puerta de gabinete no cierra herméticamente','Empaquetadura vencida en gabinete outdoor de Pisco Centro; ingreso de polvo visible en bandeja inferior. Solicitar repuesto al fabricante.','media','abierta','st-06','ACT-0007','tec-03','tec-03','2026-08-04','12:20','2026-08-15',null) on conflict (id) do nothing;
insert into incidencias (id,titulo,descripcion,severidad,estado,sitio_id,actividad_id,reportado_por,asignado_a,fecha,hora,fecha_limite,fecha_resolucion) values ('INC-2026-035','Alarma de puerta intermitente','Sensor magnético de puerta flojo en Chincha Alta generaba alarmas falsas al NOC. Se reajustó y probó con 10 aperturas.','media','resuelta','st-10',null,'tec-06','tec-06','2026-07-28','15:05','2026-08-05','2026-08-01') on conflict (id) do nothing;
insert into incidencias (id,titulo,descripcion,severidad,estado,sitio_id,actividad_id,reportado_por,asignado_a,fecha,hora,fecha_limite,fecha_resolucion) values ('INC-2026-040','Malla de cerco perimetral suelta','Tramo de 4 m de malla olímpica suelto en el lado norte del sitio Subtanjalla. Sin riesgo inmediato; era parte de observaciones del TSS y fue absorbida por la obra civil.','baja','cancelada','st-02','ACT-0001','tec-01','tec-05','2026-08-01','10:30','2026-08-20',null) on conflict (id) do nothing;

-- Materiales
insert into materiales (id,nombre,categoria,unidad,stock,minimo,almacen) values ('MAT-001','Cable coaxial 7/8" (rollo 50 m)','RF','rollo',12,4,'Almacén Ica') on conflict (id) do nothing;
insert into materiales (id,nombre,categoria,unidad,stock,minimo,almacen) values ('MAT-002','Jumper 1/2" × 3 m, 4.3-10 M-M','RF','und',48,20,'Almacén Ica') on conflict (id) do nothing;
insert into materiales (id,nombre,categoria,unidad,stock,minimo,almacen) values ('MAT-003','Conector 4.3-10 macho para 1/2"','RF','und',6,24,'Almacén Ica') on conflict (id) do nothing;
insert into materiales (id,nombre,categoria,unidad,stock,minimo,almacen) values ('MAT-004','Antena sectorial 4T4R 698–2690 MHz','RF','und',9,3,'Almacén Ica') on conflict (id) do nothing;
insert into materiales (id,nombre,categoria,unidad,stock,minimo,almacen) values ('MAT-005','RRU 5G n78 32T32R','Radio','und',0,2,'Almacén Ica') on conflict (id) do nothing;
insert into materiales (id,nombre,categoria,unidad,stock,minimo,almacen) values ('MAT-006','Banco de baterías 48 V 155 Ah','Energía','banco',3,2,'Almacén Pisco') on conflict (id) do nothing;
insert into materiales (id,nombre,categoria,unidad,stock,minimo,almacen) values ('MAT-007','Rectificador 48 V / 3000 W','Energía','und',0,1,'Almacén Ica') on conflict (id) do nothing;
insert into materiales (id,nombre,categoria,unidad,stock,minimo,almacen) values ('MAT-008','Kit puesta a tierra (varilla + Cadweld)','Obra','kit',15,5,'Almacén Ica') on conflict (id) do nothing;
insert into materiales (id,nombre,categoria,unidad,stock,minimo,almacen) values ('MAT-009','Pintura epóxica gris RAL 7035 (galón)','Obra','gal',2,6,'Almacén Pisco') on conflict (id) do nothing;
insert into materiales (id,nombre,categoria,unidad,stock,minimo,almacen) values ('MAT-010','Pernería M16 galvanizada + bridas','Obra','und',120,40,'Almacén Ica') on conflict (id) do nothing;

-- Kardex: movimientos de almacén
insert into movimientos_material (material_id,tipo,cantidad,actividad_id,sitio_id,usuario,fecha,hora) select 'MAT-002','despacho',6,'ACT-0005','st-02','Almacén Ica','2026-08-04','07:35' where not exists (select 1 from movimientos_material where material_id='MAT-002' and fecha='2026-08-04' and hora='07:35' and cantidad=6);
insert into movimientos_material (material_id,tipo,cantidad,actividad_id,sitio_id,usuario,fecha,hora) select 'MAT-006','despacho',1,'ACT-0010','st-08','Almacén Pisco','2026-08-06','07:20' where not exists (select 1 from movimientos_material where material_id='MAT-006' and fecha='2026-08-06' and hora='07:20' and cantidad=1);
insert into movimientos_material (material_id,tipo,cantidad,actividad_id,sitio_id,usuario,fecha,hora) select 'MAT-010','despacho',24,'ACT-0015','st-14','Almacén Ica','2026-08-08','06:50' where not exists (select 1 from movimientos_material where material_id='MAT-010' and fecha='2026-08-08' and hora='06:50' and cantidad=24);
insert into movimientos_material (material_id,tipo,cantidad,actividad_id,sitio_id,usuario,fecha,hora) select 'MAT-003','despacho',18,'ACT-0004','st-02','Almacén Ica','2026-08-03','07:10' where not exists (select 1 from movimientos_material where material_id='MAT-003' and fecha='2026-08-03' and hora='07:10' and cantidad=18);
insert into movimientos_material (material_id,tipo,cantidad,actividad_id,sitio_id,usuario,fecha,hora) select 'MAT-005','despacho',3,'ACT-0004','st-02','Almacén Ica','2026-08-03','07:10' where not exists (select 1 from movimientos_material where material_id='MAT-005' and fecha='2026-08-03' and hora='07:10' and cantidad=3);
insert into movimientos_material (material_id,tipo,cantidad,actividad_id,sitio_id,usuario,fecha,hora) select 'MAT-006','ingreso',2,null,null,'Compras Lima','2026-08-01','10:40' where not exists (select 1 from movimientos_material where material_id='MAT-006' and fecha='2026-08-01' and hora='10:40' and cantidad=2);
insert into movimientos_material (material_id,tipo,cantidad,actividad_id,sitio_id,usuario,fecha,hora) select 'MAT-004','despacho',3,'ACT-0003','st-02','Almacén Ica','2026-07-31','06:45' where not exists (select 1 from movimientos_material where material_id='MAT-004' and fecha='2026-07-31' and hora='06:45' and cantidad=3);
insert into movimientos_material (material_id,tipo,cantidad,actividad_id,sitio_id,usuario,fecha,hora) select 'MAT-001','ingreso',6,null,null,'Compras Lima','2026-07-28','09:15' where not exists (select 1 from movimientos_material where material_id='MAT-001' and fecha='2026-07-28' and hora='09:15' and cantidad=6);

-- Evidencias (los archivos demo apuntan a imágenes públicas de placeholder)
insert into evidencias (id,actividad_id,tipo,titulo,archivo,fecha,hora,subido_por,estado) values ('EV-0001','ACT-0005','foto_antes','Escalerilla antes del tendido','https://picsum.photos/seed/nettops-ev1/640/480','2026-08-04','08:22','tec-02','aprobada') on conflict (id) do nothing;
insert into evidencias (id,actividad_id,tipo,titulo,archivo,fecha,hora,subido_por,estado) values ('EV-0002','ACT-0005','foto_despues','Jumpers rotulados y peinados','https://picsum.photos/seed/nettops-ev2/640/480','2026-08-04','11:28','tec-02','aprobada') on conflict (id) do nothing;
insert into evidencias (id,actividad_id,tipo,titulo,archivo,fecha,hora,subido_por,estado) values ('EV-0003','ACT-0007','foto_despues','Bornes limpios y engrasados','https://picsum.photos/seed/nettops-ev3/640/480','2026-08-04','12:30','tec-03','aprobada') on conflict (id) do nothing;
insert into evidencias (id,actividad_id,tipo,titulo,archivo,fecha,hora,subido_por,estado) values ('EV-0004','ACT-0010','foto_antes','Banco de baterías retirado','https://picsum.photos/seed/nettops-ev4/640/480','2026-08-06','08:11','tec-06','aprobada') on conflict (id) do nothing;
insert into evidencias (id,actividad_id,tipo,titulo,archivo,fecha,hora,subido_por,estado) values ('EV-0005','ACT-0010','foto_despues','Banco nuevo instalado y conectado','https://picsum.photos/seed/nettops-ev5/640/480','2026-08-06','11:52','tec-06','en_revision') on conflict (id) do nothing;
insert into evidencias (id,actividad_id,tipo,titulo,archivo,fecha,hora,subido_por,estado) values ('EV-0006','ACT-0013','foto_antes','Gabinete antes de comisionar','https://picsum.photos/seed/nettops-ev6/640/480','2026-08-08','08:25','tec-07','en_revision') on conflict (id) do nothing;
insert into evidencias (id,actividad_id,tipo,titulo,archivo,fecha,hora,subido_por,estado) values ('EV-0007','ACT-0014','foto_antes','Filtros de A/A saturados','https://picsum.photos/seed/nettops-ev7/640/480','2026-08-08','08:15','tec-03','en_revision') on conflict (id) do nothing;
insert into evidencias (id,actividad_id,tipo,titulo,archivo,fecha,hora,subido_por,estado) values ('EV-0008','ACT-0002','reporte','Acta de instalación firmada','https://picsum.photos/seed/nettops-ev8/640/480','2026-07-29','15:50','tec-05','aprobada') on conflict (id) do nothing;

-- Historial
insert into historial (fecha,hora,usuario,accion,entidad,detalle) select '2026-07-29','15:55','César Yataco','actividad_completada','ACT-0002','Completó instalación de gabinete outdoor en IC-SUBTANJALLA-0117' where not exists (select 1 from historial where entidad='ACT-0002' and fecha='2026-07-29' and hora='15:55' and accion='actividad_completada');
insert into historial (fecha,hora,usuario,accion,entidad,detalle) select '2026-07-31','09:40','Alberto Peña','incidencia_creada','INC-2026-038','Reportó rectificador fuera de servicio en IC-PARCONA-0233, severidad crítica' where not exists (select 1 from historial where entidad='INC-2026-038' and fecha='2026-07-31' and hora='09:40' and accion='incidencia_creada');
insert into historial (fecha,hora,usuario,accion,entidad,detalle) select '2026-08-01','08:30','Ing. Carlos Bendezú','proyecto_actualizado','PRY-2026-009','Arrancó fase 1 (surveys) del corredor Nazca–Palpa' where not exists (select 1 from historial where entidad='PRY-2026-009' and fecha='2026-08-01' and hora='08:30' and accion='proyecto_actualizado');
insert into historial (fecha,hora,usuario,accion,entidad,detalle) select '2026-08-02','09:00','María Alejandra Grados','actividad_cancelada','ACT-0030','Canceló puesta a tierra en Vista Alegre; se unificará con adecuación de torre' where not exists (select 1 from historial where entidad='ACT-0030' and fecha='2026-08-02' and hora='09:00' and accion='actividad_cancelada');
insert into historial (fecha,hora,usuario,accion,entidad,detalle) select '2026-08-03','13:10','Marco Ccahuana','actividad_completada','ACT-0004','Completó instalación de 3 RRU n78 en IC-SUBTANJALLA-0117' where not exists (select 1 from historial where entidad='ACT-0004' and fecha='2026-08-03' and hora='13:10' and accion='actividad_completada');
insert into historial (fecha,hora,usuario,accion,entidad,detalle) select '2026-08-04','11:35','Marco Ccahuana','actividad_completada','ACT-0005','Completó tendido de jumpers y fibra en IC-SUBTANJALLA-0117 (3h20)' where not exists (select 1 from historial where entidad='ACT-0005' and fecha='2026-08-04' and hora='11:35' and accion='actividad_completada');
insert into historial (fecha,hora,usuario,accion,entidad,detalle) select '2026-08-04','12:20','Jorge Aparcana','incidencia_creada','INC-2026-042','Reportó empaquetadura vencida en gabinete de IC-PISCO-0342' where not exists (select 1 from historial where entidad='INC-2026-042' and fecha='2026-08-04' and hora='12:20' and accion='incidencia_creada');
insert into historial (fecha,hora,usuario,accion,entidad,detalle) select '2026-08-05','11:50','Lucía Uchuya','actividad_completada','ACT-0006','Completó medición de PIM en IC-ICA-0201' where not exists (select 1 from historial where entidad='ACT-0006' and fecha='2026-08-05' and hora='11:50' and accion='actividad_completada');
insert into historial (fecha,hora,usuario,accion,entidad,detalle) select '2026-08-05','16:20','Ing. Carlos Bendezú','actividad_retrasada','ACT-0025','Izaje suspendido por viento > 45 km/h en Los Aquijes' where not exists (select 1 from historial where entidad='ACT-0025' and fecha='2026-08-05' and hora='16:20' and accion='actividad_retrasada');
insert into historial (fecha,hora,usuario,accion,entidad,detalle) select '2026-08-06','11:15','César Yataco','incidencia_creada','INC-2026-041','Reportó corrosión severa en pernos de torreta (IC-NAZCA-0509), severidad alta' where not exists (select 1 from historial where entidad='INC-2026-041' and fecha='2026-08-06' and hora='11:15' and accion='incidencia_creada');
insert into historial (fecha,hora,usuario,accion,entidad,detalle) select '2026-08-06','11:55','Alberto Peña','actividad_completada','ACT-0010','Completó cambio de banco de baterías en IC-TUPACAMARU-0125' where not exists (select 1 from historial where entidad='ACT-0010' and fecha='2026-08-06' and hora='11:55' and accion='actividad_completada');
insert into historial (fecha,hora,usuario,accion,entidad,detalle) select '2026-08-06','18:30','Ing. Carmen Falconí','actividad_retrasada','ACT-0026','Reprogramación pendiente: cuadrilla retenida en correctivo' where not exists (select 1 from historial where entidad='ACT-0026' and fecha='2026-08-06' and hora='18:30' and accion='actividad_retrasada');
insert into historial (fecha,hora,usuario,accion,entidad,detalle) select '2026-08-07','12:55','Jorge Aparcana','actividad_completada','ACT-0012','Completó preventivo en IC-SUNAMPE-0176 sin evidencia fotográfica' where not exists (select 1 from historial where entidad='ACT-0012' and fecha='2026-08-07' and hora='12:55' and accion='actividad_completada');
insert into historial (fecha,hora,usuario,accion,entidad,detalle) select '2026-08-07','13:20','Katherine Ramos','actividad_completada','ACT-0011','Completó Drive test clúster Ica centro (6h17 de recorrido)' where not exists (select 1 from historial where entidad='ACT-0011' and fecha='2026-08-07' and hora='13:20' and accion='actividad_completada');
insert into historial (fecha,hora,usuario,accion,entidad,detalle) select '2026-08-07','17:40','María Alejandra Grados','actividad_retrasada','ACT-0027','Marcó como retrasada: analizador PIM en calibración' where not exists (select 1 from historial where entidad='ACT-0027' and fecha='2026-08-07' and hora='17:40' and accion='actividad_retrasada');
insert into historial (fecha,hora,usuario,accion,entidad,detalle) select '2026-08-08','07:45','César Yataco','actividad_iniciada','ACT-0015','Inició Adecuación estructural en IC-NAZCA-0509' where not exists (select 1 from historial where entidad='ACT-0015' and fecha='2026-08-08' and hora='07:45' and accion='actividad_iniciada');
insert into historial (fecha,hora,usuario,accion,entidad,detalle) select '2026-08-08','08:05','Jorge Aparcana','actividad_iniciada','ACT-0014','Inició Mantenimiento preventivo en IC-PUEBLONUEVO-0083' where not exists (select 1 from historial where entidad='ACT-0014' and fecha='2026-08-08' and hora='08:05' and accion='actividad_iniciada');
insert into historial (fecha,hora,usuario,accion,entidad,detalle) select '2026-08-08','08:12','Milagros Huarcaya','actividad_iniciada','ACT-0013','Inició Comisionamiento 5G NSA en IC-SUBTANJALLA-0117' where not exists (select 1 from historial where entidad='ACT-0013' and fecha='2026-08-08' and hora='08:12' and accion='actividad_iniciada');
insert into historial (fecha,hora,usuario,accion,entidad,detalle) select '2026-08-08','08:15','Jorge Aparcana','evidencia_subida','EV-0007','Subió foto "Filtros de A/A saturados" a ACT-0014 (IC-PUEBLONUEVO-0083)' where not exists (select 1 from historial where entidad='EV-0007' and fecha='2026-08-08' and hora='08:15' and accion='evidencia_subida');
insert into historial (fecha,hora,usuario,accion,entidad,detalle) select '2026-08-08','08:25','Milagros Huarcaya','evidencia_subida','EV-0006','Subió foto "Gabinete antes de comisionar" a ACT-0013 (IC-SUBTANJALLA-0117)' where not exists (select 1 from historial where entidad='EV-0006' and fecha='2026-08-08' and hora='08:25' and accion='evidencia_subida');

-- Notificaciones
insert into notificaciones (tipo,titulo,detalle,link,fecha,hora,leida) select 'completado','Cambio de baterías completado','ACT-0010 · IC-TUPACAMARU-0125, autonomía verificada 4h10.','actividades.html','2026-08-06','12:00',true where not exists (select 1 from notificaciones where titulo='Cambio de baterías completado' and fecha='2026-08-06' and hora='12:00');
insert into notificaciones (tipo,titulo,detalle,link,fecha,hora,leida) select 'critico','Nueva incidencia alta en Nazca','INC-2026-041 · Corrosión severa en pernos de torreta, límite 12/08.','incidencias.html','2026-08-06','11:20',true where not exists (select 1 from notificaciones where titulo='Nueva incidencia alta en Nazca' and fecha='2026-08-06' and hora='11:20');
insert into notificaciones (tipo,titulo,detalle,link,fecha,hora,leida) select 'pendiente','Actividad retrasada por calibración','ACT-0027 · Medición PIM en Subtanjalla; analizador retorna el 10/08.','actividades.html','2026-08-07','17:45',true where not exists (select 1 from notificaciones where titulo='Actividad retrasada por calibración' and fecha='2026-08-07' and hora='17:45');
insert into notificaciones (tipo,titulo,detalle,link,fecha,hora,leida) select 'completado','Drive test completado','ACT-0011 · Clúster Ica centro, RSRP promedio -84 dBm. Log entregado.','actividades.html','2026-08-07','13:25',true where not exists (select 1 from notificaciones where titulo='Drive test completado' and fecha='2026-08-07' and hora='13:25');
insert into notificaciones (tipo,titulo,detalle,link,fecha,hora,leida) select 'ejecucion','3 actividades en ejecución','Comisionamiento 5G (Subtanjalla), preventivo (Pueblo Nuevo) y adecuación (Nazca) en curso.','actividades.html','2026-08-08','08:15',false where not exists (select 1 from notificaciones where titulo='3 actividades en ejecución' and fecha='2026-08-08' and hora='08:15');
insert into notificaciones (tipo,titulo,detalle,link,fecha,hora,leida) select 'pendiente','2 evidencias esperan revisión','EV-0005 y EV-0006 subidas desde campo requieren aprobación del supervisor.','evidencias.html','2026-08-08','08:30',false where not exists (select 1 from notificaciones where titulo='2 evidencias esperan revisión' and fecha='2026-08-08' and hora='08:30');
insert into notificaciones (tipo,titulo,detalle,link,fecha,hora,leida) select 'critico','Material sin stock bloquea correctivo','MAT-007 Rectificador 48V/3000W en 0 unidades. ACT-0024 sigue retrasada.','materiales.html','2026-08-08','07:00',false where not exists (select 1 from notificaciones where titulo='Material sin stock bloquea correctivo' and fecha='2026-08-08' and hora='07:00');
insert into notificaciones (tipo,titulo,detalle,link,fecha,hora,leida) select 'critico','Incidencia crítica vencida hace 6 días','INC-2026-038 · Rectificador fuera de servicio en IC-PARCONA-0233. Límite: 02/08.','incidencias.html','2026-08-08','07:00',false where not exists (select 1 from notificaciones where titulo='Incidencia crítica vencida hace 6 días' and fecha='2026-08-08' and hora='07:00');
insert into notificaciones (tipo,titulo,detalle,link,fecha,hora,leida) select 'pendiente','Cierre pendiente de aprobación','ACT-0012 · Preventivo en IC-SUNAMPE-0176 espera revisión del supervisor (sin evidencia fotográfica).','actividades.html','2026-08-08','07:30',false where not exists (select 1 from notificaciones where titulo='Cierre pendiente de aprobación' and fecha='2026-08-08' and hora='07:30');

-- ─────────────────────────────────────────────────────────────────────────
-- Resumen de lo cargado
select 'clientes' t, count(*) from clientes
union all select 'proyectos', count(*) from proyectos
union all select 'sitios', count(*) from sitios
union all select 'tecnicos', count(*) from tecnicos
union all select 'tipos_actividad', count(*) from tipos_actividad
union all select 'actividades', count(*) from actividades
union all select 'checklist_items', count(*) from checklist_items
union all select 'incidencias', count(*) from incidencias
union all select 'materiales', count(*) from materiales
union all select 'movimientos', count(*) from movimientos_material
union all select 'evidencias', count(*) from evidencias
union all select 'historial', count(*) from historial
union all select 'notificaciones', count(*) from notificaciones;
